baseurl: https://daorui-han.netlify.app/
title: DAORUI HAN
theme: hugo-theme-console
languageCode: en-us
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about
      url: about/
    - name: publications
      url: articles/
    - name: project
      url: photos/
    - name: life
      url: life/
   
  titleCutting: no
